### ISSUE TITLE
HDBDOS not building correctly ROM's incorrect size

### ISSUE THREAD

**Issue by drencorxeen** [nitros9project/toolshed#9]
Attempted to build current sources for HDBDOS and the file size for HDBDOS ROM's is incorrect.

**Comment by strickyak** [comment]
One solution is in https://github.com/nitros9project/toolshed/pull/10
I'm trying to get permission to check it in.

**Comment by strickyak** [comment]
This should be fixed now, David. 
Let me know if it still has problems!
